server:
  port: 8181
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gradle-demo
    username: postgres
    password: postgres
    hikari:
      driver-class-name: org.postgresql.Driver
      connection-timeout: 30000
      maximum-pool-size: 500
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-test-query: SELECT 1;
      validation-timeout: 28000
  jpa:
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: true
    generate-ddl: false
    open-in-view: false
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        format_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
  flyway:
    enabled: true
app:
  configuration:
    retry:
      max-attempts: 1000
      delay: 1
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
        internal:
          ExceptionMapperStandardImpl: off
